# **Project Name**    - Vaccination Data Analysis

##### **Project Type**    - EDA
##### **Contribution**    - Individual
##### **By**              - Atharav Satishkumar Kadam

# **Project Summary -**


**Vaccination Data Analysis and Visualization** is a public health analytics project focused on analyzing global vaccination coverage, disease incidence, reported cases, vaccine introduction, and vaccination schedules. The project aims to identify vaccination trends, regional disparities, and relationships between vaccination coverage and disease reduction.

The project involves **data cleaning, exploratory data analysis (EDA), SQL database management, and Power BI visualization**. Raw vaccination and disease-related data is cleaned by handling missing values, standardizing units, and maintaining consistent date formats. The cleaned data is then organized into normalized relational SQL tables with appropriate primary and foreign-key relationships.

Power BI is connected to the SQL database to create interactive dashboards containing **KPI indicators, geographical heatmaps, trend charts, bar charts, and scatter plots**. These visualizations help analyze vaccination coverage over time, disease incidence across regions, and the relationship between vaccination rates and disease outcomes.

The analysis explores important public health questions, including vaccination coverage disparities, first-dose to subsequent-dose drop-off, booster uptake, urban-rural differences, vaccine introduction timelines, and disease reduction following vaccination campaigns. The project also supports practical use cases such as identifying low-coverage regions, improving resource allocation, estimating vaccine demand, and evaluating vaccination strategies.

The final deliverables include **Python scripts for data cleaning and extraction, SQL queries and a structured database, interactive Power BI dashboards, and project documentation**. Overall, the project demonstrates how data analytics and visualization can transform vaccination and disease data into meaningful insights for public health planning and decision-making.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

The project aims to analyze global vaccination data to understand vaccination coverage, disease incidence, and the effectiveness of vaccination programs. The data will be cleaned and stored in a structured SQL database, followed by analysis and visualization using Power BI. The project will identify vaccination trends, regional disparities, and relationships between vaccination coverage and disease control to support public health strategies, resource allocation, and disease prevention.

#### **Define Your Business Objective?**

The main business objective of this project is to use vaccination and disease data to generate actionable insights that can help public health organizations make better decisions.

Key objectives include:

Evaluate vaccination programs across different regions and populations.
Identify areas with low vaccination coverage and support targeted interventions.
Analyze disease incidence and identify diseases that remain prevalent despite vaccination efforts.
Improve resource allocation by identifying regions and high-risk populations that require greater vaccination support.
Forecast vaccine demand based on historical vaccination trends.
Support public health policy with data-driven insights about vaccination effectiveness and disease prevention.

###Let's Begin

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
converge=pd.read_excel(r'/content/drive/MyDrive/Labmentix Projects/Vaccination_Data_Analysis/coverage-data.xlsx')

In [ ]:
incidence = pd.read_excel(
    r'/content/drive/MyDrive/Labmentix Projects/Vaccination_Data_Analysis/incidence-rate-data.xlsx'
)

reported = pd.read_excel(
    r'/content/drive/MyDrive/Labmentix Projects/Vaccination_Data_Analysis/reported-cases-data.xlsx'
)

vaccine_introduction = pd.read_excel(
    r'/content/drive/MyDrive/Labmentix Projects/Vaccination_Data_Analysis/vaccine-introduction-data.xlsx'
)

vaccine_schedule = pd.read_excel(
    r'/content/drive/MyDrive/Labmentix Projects/Vaccination_Data_Analysis/vaccine-schedule-data.xlsx'
)

In [ ]:
converge.shape

(399859, 11)

In [ ]:
incidence.shape

(84946, 8)

In [ ]:
reported.shape

(84870, 7)

In [ ]:
vaccine_introduction.shape

(138321, 6)

In [ ]:
vaccine_schedule.shape

(8053, 12)

In [ ]:
converge.head()

,GROUP,CODE,NAME,YEAR,ANTIGEN,ANTIGEN_DESCRIPTION,COVERAGE_CATEGORY,COVERAGE_CATEGORY_DESCRIPTION,TARGET_NUMBER,DOSES,COVERAGE
0,COUNTRIES,ABW,Aruba,2023.0,BCG,BCG,ADMIN,Administrative coverage,NaN,NaN,NaN
1,COUNTRIES,ABW,Aruba,2023.0,BCG,BCG,OFFICIAL,Official coverage,NaN,NaN,NaN
2,COUNTRIES,ABW,Aruba,2023.0,DIPHCV4,"Diphtheria-containing vaccine, 4th dose (1st b...",ADMIN,Administrative coverage,1044.0,945.0,90.52
3,COUNTRIES,ABW,Aruba,2023.0,DIPHCV4,"Diphtheria-containing vaccine, 4th dose (1st b...",OFFICIAL,Official coverage,NaN,NaN,90.52
4,COUNTRIES,ABW,Aruba,2023.0,DIPHCV5,"Diphtheria-containing vaccine, 5th dose (2nd b...",ADMIN,Administrative coverage,1219.0,1008.0,82.69

In [ ]:
datasets = {
    "Coverage": converge,
    "Vaccine Schedule": vaccine_schedule,
    "Vaccine Introduction": vaccine_introduction,
    "Reported Cases": reported,
    "Incidence": incidence
}

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print("\nFirst 5 rows:")
    display(df.head())

============================================================
Coverage
============================================================
Shape: (399859, 11)
Columns: ['GROUP', 'CODE', 'NAME', 'YEAR', 'ANTIGEN', 'ANTIGEN_DESCRIPTION', 'COVERAGE_CATEGORY', 'COVERAGE_CATEGORY_DESCRIPTION', 'TARGET_NUMBER', 'DOSES', 'COVERAGE']

First 5 rows:

,GROUP,CODE,NAME,YEAR,ANTIGEN,ANTIGEN_DESCRIPTION,COVERAGE_CATEGORY,COVERAGE_CATEGORY_DESCRIPTION,TARGET_NUMBER,DOSES,COVERAGE
0,COUNTRIES,ABW,Aruba,2023.0,BCG,BCG,ADMIN,Administrative coverage,NaN,NaN,NaN
1,COUNTRIES,ABW,Aruba,2023.0,BCG,BCG,OFFICIAL,Official coverage,NaN,NaN,NaN
2,COUNTRIES,ABW,Aruba,2023.0,DIPHCV4,"Diphtheria-containing vaccine, 4th dose (1st b...",ADMIN,Administrative coverage,1044.0,945.0,90.52
3,COUNTRIES,ABW,Aruba,2023.0,DIPHCV4,"Diphtheria-containing vaccine, 4th dose (1st b...",OFFICIAL,Official coverage,NaN,NaN,90.52
4,COUNTRIES,ABW,Aruba,2023.0,DIPHCV5,"Diphtheria-containing vaccine, 5th dose (2nd b...",ADMIN,Administrative coverage,1219.0,1008.0,82.69

============================================================
Vaccine Schedule
============================================================
Shape: (8053, 12)
Columns: ['ISO_3_CODE', 'COUNTRYNAME', 'WHO_REGION', 'YEAR', 'VACCINECODE', 'VACCINE_DESCRIPTION', 'SCHEDULEROUNDS', 'TARGETPOP', 'TARGETPOP_DESCRIPTION', 'GEOAREA', 'AGEADMINISTERED', 'SOURCECOMMENT']

First 5 rows:

,ISO_3_CODE,COUNTRYNAME,WHO_REGION,YEAR,VACCINECODE,VACCINE_DESCRIPTION,SCHEDULEROUNDS,TARGETPOP,TARGETPOP_DESCRIPTION,GEOAREA,AGEADMINISTERED,SOURCECOMMENT
0,ABW,Aruba,AMRO,2023.0,DTAPHIBIPV,DTaP-Hib-IPV (acellular) vaccine,1.0,NaN,General/routine,NATIONAL,M2,NaN
1,ABW,Aruba,AMRO,2023.0,DTAPHIBIPV,DTaP-Hib-IPV (acellular) vaccine,2.0,NaN,General/routine,NATIONAL,M4,NaN
2,ABW,Aruba,AMRO,2023.0,DTAPHIBIPV,DTaP-Hib-IPV (acellular) vaccine,3.0,NaN,General/routine,NATIONAL,M6,NaN
3,ABW,Aruba,AMRO,2023.0,DTAPHIBIPV,DTaP-Hib-IPV (acellular) vaccine,4.0,B_2YL_W,General/routine,NATIONAL,M15,NaN
4,ABW,Aruba,AMRO,2023.0,DTAPIPV,DTaP-IPV (acellular) vaccine,5.0,B_CHILD_W,General/routine,NATIONAL,Y4,NaN

============================================================
Vaccine Introduction
============================================================
Shape: (138321, 6)
Columns: ['ISO_3_CODE', 'COUNTRYNAME', 'WHO_REGION', 'YEAR', 'DESCRIPTION', 'INTRO']

First 5 rows:

,ISO_3_CODE,COUNTRYNAME,WHO_REGION,YEAR,DESCRIPTION,INTRO
0,AFG,Afghanistan,EMRO,2023.0,aP (acellular pertussis) vaccine,No
1,AFG,Afghanistan,EMRO,2023.0,Hepatitis A vaccine,No
2,AFG,Afghanistan,EMRO,2023.0,Hepatitis B vaccine,Yes
3,AFG,Afghanistan,EMRO,2023.0,HepB birth dose,Yes
4,AFG,Afghanistan,EMRO,2023.0,Hib (Haemophilus influenzae type B) vaccine,Yes

============================================================
Reported Cases
============================================================
Shape: (84870, 7)
Columns: ['GROUP', 'CODE', 'NAME', 'YEAR', 'DISEASE', 'DISEASE_DESCRIPTION', 'CASES']

First 5 rows:

,GROUP,CODE,NAME,YEAR,DISEASE,DISEASE_DESCRIPTION,CASES
0,COUNTRIES,ABW,Aruba,2023.0,CRS,Congenital rubella syndrome,0.0
1,COUNTRIES,ABW,Aruba,2023.0,DIPHTHERIA,Diphtheria,0.0
2,COUNTRIES,ABW,Aruba,2023.0,INVASIVE_MENING,Invasive meningococcal disease,1.0
3,COUNTRIES,ABW,Aruba,2023.0,MEASLES,Measles,NaN
4,COUNTRIES,ABW,Aruba,2023.0,MUMPS,Mumps,0.0

============================================================
Incidence
============================================================
Shape: (84946, 8)
Columns: ['GROUP', 'CODE', 'NAME', 'YEAR', 'DISEASE', 'DISEASE_DESCRIPTION', 'DENOMINATOR', 'INCIDENCE_RATE']

First 5 rows:

,GROUP,CODE,NAME,YEAR,DISEASE,DISEASE_DESCRIPTION,DENOMINATOR,INCIDENCE_RATE
0,COUNTRIES,ABW,Aruba,2023.0,CRS,Congenital rubella syndrome,"per 10,000 live births",0.0
1,COUNTRIES,ABW,Aruba,2023.0,DIPHTHERIA,Diphtheria,"per 1,000,000 total population",0.0
2,COUNTRIES,ABW,Aruba,2023.0,INVASIVE_MENING,Invasive meningococcal disease,"per 1,000,000 total population",9.3
3,COUNTRIES,ABW,Aruba,2023.0,MEASLES,Measles,"per 1,000,000 total population",NaN
4,COUNTRIES,ABW,Aruba,2023.0,MUMPS,Mumps,"per 1,000,000 total population",0.0

In [ ]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print(df.dtypes)

============================================================
Coverage
============================================================
GROUP                             object
CODE                              object
NAME                              object
YEAR                             float64
ANTIGEN                           object
ANTIGEN_DESCRIPTION               object
COVERAGE_CATEGORY                 object
COVERAGE_CATEGORY_DESCRIPTION     object
TARGET_NUMBER                    float64
DOSES                            float64
COVERAGE                         float64
dtype: object

============================================================
Vaccine Schedule
============================================================
ISO_3_CODE                object
COUNTRYNAME               object
WHO_REGION                object
YEAR                     float64
VACCINECODE               object
VACCINE_DESCRIPTION       object
SCHEDULEROUNDS           float64
TARGETPOP                 object
TARGETPOP_DESCRIPTION     object
GEOAREA                   object
AGEADMINISTERED           object
SOURCECOMMENT             object
dtype: object

============================================================
Vaccine Introduction
============================================================
ISO_3_CODE      object
COUNTRYNAME     object
WHO_REGION      object
YEAR           float64
DESCRIPTION     object
INTRO           object
dtype: object

============================================================
Reported Cases
============================================================
GROUP                   object
CODE                    object
NAME                    object
YEAR                   float64
DISEASE                 object
DISEASE_DESCRIPTION     object
CASES                  float64
dtype: object

============================================================
Incidence
============================================================
GROUP                   object
CODE                    object
NAME                    object
YEAR                   float64
DISEASE                 object
DISEASE_DESCRIPTION     object
DENOMINATOR             object
INCIDENCE_RATE         float64
dtype: object

In [ ]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    missing = df.isnull().sum()
    missing_percent = (df.isnull().sum() / len(df)) * 100

    missing_table = pd.DataFrame({
        "Missing Values": missing,
        "Missing Percentage": missing_percent.round(2)
    })

    display(
        missing_table[missing_table["Missing Values"] > 0]
        .sort_values("Missing Values", ascending=False)
    )

============================================================
Coverage
============================================================

                               Missing Values  Missing Percentage
TARGET_NUMBER                          320829               80.24
DOSES                                  320532               80.16
COVERAGE                               169382               42.36
NAME                                     1275                0.32
CODE                                        1                0.00
YEAR                                        1                0.00
COVERAGE_CATEGORY                           1                0.00
ANTIGEN_DESCRIPTION                         1                0.00
ANTIGEN                                     1                0.00
COVERAGE_CATEGORY_DESCRIPTION               1                0.00

============================================================
Vaccine Schedule
============================================================

                       Missing Values  Missing Percentage
TARGETPOP                        4258               52.87
SOURCECOMMENT                    2914               36.19
AGEADMINISTERED                  1046               12.99
GEOAREA                            31                0.38
YEAR                                1                0.01
COUNTRYNAME                         1                0.01
WHO_REGION                          1                0.01
SCHEDULEROUNDS                      1                0.01
VACCINE_DESCRIPTION                 1                0.01
VACCINECODE                         1                0.01
TARGETPOP_DESCRIPTION               1                0.01

============================================================
Vaccine Introduction
============================================================

             Missing Values  Missing Percentage
COUNTRYNAME               1                 0.0
WHO_REGION                1                 0.0
YEAR                      1                 0.0
DESCRIPTION               1                 0.0
INTRO                     1                 0.0

============================================================
Reported Cases
============================================================

                     Missing Values  Missing Percentage
CASES                         19400               22.86
CODE                              1                0.00
NAME                              1                0.00
YEAR                              1                0.00
DISEASE                           1                0.00
DISEASE_DESCRIPTION               1                0.00

============================================================
Incidence
============================================================

                     Missing Values  Missing Percentage
INCIDENCE_RATE                23362                27.5
NAME                              1                 0.0
CODE                              1                 0.0
YEAR                              1                 0.0
DISEASE                           1                 0.0
DISEASE_DESCRIPTION               1                 0.0
DENOMINATOR                       1                 0.0

In [ ]:
for name, df in datasets.items():
    print(
        f"{name}: {df.duplicated().sum():,} duplicate rows"
    )

Coverage: 0 duplicate rows
Vaccine Schedule: 0 duplicate rows
Vaccine Introduction: 0 duplicate rows
Reported Cases: 0 duplicate rows
Incidence: 0 duplicate rows

In [ ]:
for df in datasets.values():
    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

In [ ]:
for name, df in datasets.items():
    print(name)
    print(df.columns.tolist())
    print()

Coverage
['group', 'code', 'name', 'year', 'antigen', 'antigen_description', 'coverage_category', 'coverage_category_description', 'target_number', 'doses', 'coverage']

Vaccine Schedule
['iso_3_code', 'countryname', 'who_region', 'year', 'vaccinecode', 'vaccine_description', 'schedulerounds', 'targetpop', 'targetpop_description', 'geoarea', 'ageadministered', 'sourcecomment']

Vaccine Introduction
['iso_3_code', 'countryname', 'who_region', 'year', 'description', 'intro']

Reported Cases
['group', 'code', 'name', 'year', 'disease', 'disease_description', 'cases']

Incidence
['group', 'code', 'name', 'year', 'disease', 'disease_description', 'denominator', 'incidence_rate']

In [ ]:
for name, df in datasets.items():

    if "code" in df.columns:
        df.rename(columns={"code": "iso_code"}, inplace=True)

    elif "iso_3_code" in df.columns:
        df.rename(columns={"iso_3_code": "iso_code"}, inplace=True)

In [ ]:
for name, df in datasets.items():
    print(name, "→", df.columns.tolist())

Coverage → ['group', 'iso_code', 'name', 'year', 'antigen', 'antigen_description', 'coverage_category', 'coverage_category_description', 'target_number', 'doses', 'coverage']
Vaccine Schedule → ['iso_code', 'countryname', 'who_region', 'year', 'vaccinecode', 'vaccine_description', 'schedulerounds', 'targetpop', 'targetpop_description', 'geoarea', 'ageadministered', 'sourcecomment']
Vaccine Introduction → ['iso_code', 'countryname', 'who_region', 'year', 'description', 'intro']
Reported Cases → ['group', 'iso_code', 'name', 'year', 'disease', 'disease_description', 'cases']
Incidence → ['group', 'iso_code', 'name', 'year', 'disease', 'disease_description', 'denominator', 'incidence_rate']

In [ ]:
for name, df in datasets.items():
    if "year" in df.columns:
        df["year"] = pd.to_numeric(
            df["year"],
            errors="coerce"
        ).astype("Int64")

In [ ]:
for name, df in datasets.items():
    print(name)
    print(df["year"].describe())

Coverage
count       399858.0
mean     2009.207489
std         11.72053
min           1980.0
25%           2002.0
50%           2012.0
75%           2019.0
max           2023.0
Name: year, dtype: Float64
Vaccine Schedule
count         8052.0
mean     2022.941505
std         0.441237
min           2019.0
25%           2023.0
50%           2023.0
75%           2023.0
max           2023.0
Name: year, dtype: Float64
Vaccine Introduction
count       138320.0
mean     2001.267879
std        17.679511
min           1940.0
25%           1992.0
50%           2006.0
75%           2015.0
max           2023.0
Name: year, dtype: Float64
Reported Cases
count        84869.0
mean     2004.108261
std        12.591396
min           1980.0
25%           1994.0
50%           2005.0
75%           2015.0
max           2023.0
Name: year, dtype: Float64
Incidence
count        84945.0
mean     2004.095791
std        12.595166
min           1980.0
25%           1994.0
50%           2005.0
75%           2015.0
max           2023.0
Name: year, dtype: Float64

In [ ]:
for name, df in datasets.items():

    print("\n", "=" * 50)
    print(name)

    if "year" in df.columns:
        print("Minimum Year:", df["year"].min())
        print("Maximum Year:", df["year"].max())

    if "iso_code" in df.columns:
        print("Unique Countries:", df["iso_code"].nunique())

 ==================================================
Coverage
Minimum Year: 1980
Maximum Year: 2023
Unique Countries: 245

 ==================================================
Vaccine Schedule
Minimum Year: 2019
Maximum Year: 2023
Unique Countries: 214

 ==================================================
Vaccine Introduction
Minimum Year: 1940
Maximum Year: 2023
Unique Countries: 195

 ==================================================
Reported Cases
Minimum Year: 1980
Maximum Year: 2023
Unique Countries: 221

 ==================================================
Incidence
Minimum Year: 1980
Maximum Year: 2023
Unique Countries: 221

In [ ]:
print("Antigens:")
display(converge["antigen"].value_counts().head(20))

print("\nCoverage Categories:")
display(converge["coverage_category"].value_counts())

Antigens:

antigen
DTPCV3     26015
POL3       26005
MCV1       25939
BCG        24289
HEPB3      22249
HIB3       20845
DTPCV1     19760
MCV2       19317
RCV1       17356
HEPB_BD    14982
TT2PLUS    14684
YFV        14640
VAD1       13451
ROTAC      10420
PCV3       10020
PAB         9155
JAPENC      6477
PCV1        6365
ROTA1       6345
IPV1        6114
Name: count, dtype: int64

Coverage Categories:

coverage_category
ADMIN       155576
OFFICIAL    118050
WUENIC       95560
HPV          25304
PAB           5368
Name: count, dtype: int64

In [ ]:
print("Diseases in Reported Cases:")
display(reported["disease"].value_counts().head(20))

print("\nDiseases in Incidence:")
display(incidence["disease"].value_counts().head(20))

Diseases in Reported Cases:

disease
MEASLES            9196
NTETANUS           9182
DIPHTHERIA         9181
PERTUSSIS          9181
POLIO              9129
TTETANUS           9127
YFEVER             9051
RUBELLA            5205
CRS                5153
MUMPS              5124
JAPENC             3220
TYPHOID            1280
INVASIVE_MENING     840
Name: count, dtype: int64

Diseases in Incidence:

disease
MEASLES            9196
NTETANUS           9182
DIPHTHERIA         9181
PERTUSSIS          9181
POLIO              9130
TTETANUS           9127
YFEVER             9122
RUBELLA            5205
CRS                5153
MUMPS              5124
JAPENC             3224
TYPHOID            1280
INVASIVE_MENING     840
Name: count, dtype: int64

In [ ]:
print("COVERAGE")
display(converge.describe(include="all").T)

COVERAGE

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
group,399859,9,COUNTRIES,381041,NaN,NaN,NaN,NaN,NaN,NaN,NaN
iso_code,399858,245,ETH,2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,398584,242,Ethiopia,2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,399858.0,<NA>,<NA>,<NA>,2009.207489,11.72053,1980.0,2002.0,2012.0,2019.0,2023.0
antigen,399858,69,DTPCV3,26015,NaN,NaN,NaN,NaN,NaN,NaN,NaN
antigen_description,399858,69,"DTP-containing vaccine, 3rd dose",26015,NaN,NaN,NaN,NaN,NaN,NaN,NaN
coverage_category,399858,5,ADMIN,155576,NaN,NaN,NaN,NaN,NaN,NaN,NaN
coverage_category_description,399858,5,Administrative coverage,155576,NaN,NaN,NaN,NaN,NaN,NaN,NaN
target_number,79030.0,NaN,NaN,NaN,278019173.759516,54152442883.354065,0.0,32814.0,317871.5,2493048.0,11700000000000.0
doses,79327.0,NaN,NaN,NaN,3467241.121352,11256763.030974,-222288203.0,14469.0,152212.0,971018.5,126605212.0
coverage,230477.0,NaN,NaN,NaN,78.032914,74.891697,0.0,69.32,88.79,96.0,32000.0

In [ ]:
print("REPORTED CASES")
display(reported.describe(include="all").T)

REPORTED CASES

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
group,84870,4,COUNTRIES,82054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
iso_code,84869,221,GLOBAL,424,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,84869,221,Global,424,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,84869.0,<NA>,<NA>,<NA>,2004.108261,12.591396,1980.0,1994.0,2005.0,2015.0,2023.0
disease,84869,13,MEASLES,9196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disease_description,84869,13,Measles,9196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cases,65470.0,NaN,NaN,NaN,4472.408569,61144.550256,0.0,0.0,1.0,63.0,4583555.0

In [ ]:
print("INCIDENCE")
display(incidence.describe(include="all").T)

INCIDENCE

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
group,84946,4,COUNTRIES,82054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
iso_code,84945,221,GLOBAL,424,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,84945,221,Global,424,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,84945.0,<NA>,<NA>,<NA>,2004.095791,12.595166,1980.0,1994.0,2005.0,2015.0,2023.0
disease,84945,13,MEASLES,9196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disease_description,84945,13,Measles,9196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
denominator,84945,5,"per 1,000,000 total population",61480,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incidence_rate,61584.0,NaN,NaN,NaN,109.448781,992.276983,0.0,0.0,0.0,4.6,69101.3

In [ ]:
print("Coverage minimum:", converge["coverage"].min())
print("Coverage maximum:", converge["coverage"].max())
print("Coverage mean:", converge["coverage"].mean())
print("Coverage median:", converge["coverage"].median())

Coverage minimum: 0.0
Coverage maximum: 32000.0
Coverage mean: 78.03291395670718
Coverage median: 88.79

In [ ]:
converge[
    (converge["coverage"] < 0) |
    (converge["coverage"] > 100)
].head()

,group,iso_code,name,year,antigen,antigen_description,coverage_category,coverage_category_description,target_number,doses,coverage
1247,COUNTRIES,AFG,Afghanistan,2015,DTPCV1,"DTP-containing vaccine, 1st dose",ADMIN,Administrative coverage,1429729.0,1593629.0,111.00
1248,COUNTRIES,AFG,Afghanistan,2015,DTPCV1,"DTP-containing vaccine, 1st dose",OFFICIAL,Official coverage,NaN,NaN,109.00
1275,COUNTRIES,AFG,Afghanistan,2015,PCV1,"Pneumococcal conjugate vaccine, 1st dose",ADMIN,Administrative coverage,1429729.0,1618719.0,113.00
1276,COUNTRIES,AFG,Afghanistan,2015,PCV1,"Pneumococcal conjugate vaccine, 1st dose",OFFICIAL,Official coverage,NaN,NaN,111.00
1307,COUNTRIES,AFG,Afghanistan,2014,BCG,BCG,ADMIN,Administrative coverage,1512698.0,1530282.0,101.16

In [ ]:
AGGREGATE_GROUPS = {
    "DEVELOPMENT_STATUS",
    "GAVI_PHASE5",
    "GLOBAL",
    "UNICEF_REGIONS",
    "WB_LONG",
    "WB_SHORT",
    "WHO_REGIONS"
}

for df in [converge, reported, incidence]:

    if "group" in df.columns:
        df["group_level"] = df["group"].apply(
            lambda x: "AGGREGATE"
            if str(x).upper() in AGGREGATE_GROUPS
            else "COUNTRY"
        )

In [ ]:
print(converge["group_level"].value_counts())

group_level
COUNTRY      381042
AGGREGATE     18817
Name: count, dtype: int64

In [ ]:
for name, df in datasets.items():

    duplicates = df.duplicated().sum()

    print(f"{name}: {duplicates} duplicates")

    if duplicates > 0:
        df.drop_duplicates(inplace=True)

Coverage: 0 duplicates
Vaccine Schedule: 0 duplicates
Vaccine Introduction: 0 duplicates
Reported Cases: 0 duplicates
Incidence: 0 duplicates

In [ ]:
from pathlib import Path

OUTPUT_DIR = Path(
    "/content/drive/MyDrive/Labmentix Projects/Vaccination_Data_Analysis/cleaned_data"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [ ]:
converge.to_csv(
    OUTPUT_DIR / "coverage_clean.csv",
    index=False
)

vaccine_schedule.to_csv(
    OUTPUT_DIR / "vaccine_schedule_clean.csv",
    index=False
)

vaccine_introduction.to_csv(
    OUTPUT_DIR / "vaccine_introduction_clean.csv",
    index=False
)

reported.to_csv(
    OUTPUT_DIR / "reported_clean.csv",
    index=False
)

incidence.to_csv(
    OUTPUT_DIR / "incidence_clean.csv",
    index=False
)

print("All cleaned datasets saved successfully!")

All cleaned datasets saved successfully!

In [ ]:
# ============================================================
# BUILD SQL DATABASE
# ============================================================

import sqlite3
import pandas as pd
from pathlib import Path


# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

CLEAN_DIR = Path(
    "/content/drive/MyDrive/Labmentix Projects/"
    "Vaccination_Data_Analysis/cleaned_data"
)

DB_PATH = CLEAN_DIR / "vaccination.db"

print("Clean data directory:")
print(CLEAN_DIR)

print("\nDatabase:")
print(DB_PATH)


# ------------------------------------------------------------
# 2. LOAD CLEANED CSV FILES
# ------------------------------------------------------------

tables = {
    "coverage": pd.read_csv(
        CLEAN_DIR / "coverage_clean.csv"
    ),

    "schedule": pd.read_csv(
        CLEAN_DIR / "vaccine_schedule_clean.csv"
    ),

    "introduction": pd.read_csv(
        CLEAN_DIR / "vaccine_introduction_clean.csv"
    ),

    "cases": pd.read_csv(
        CLEAN_DIR / "reported_clean.csv"
    ),

    "incidence": pd.read_csv(
        CLEAN_DIR / "incidence_clean.csv"
    )
}


# ------------------------------------------------------------
# 3. DISPLAY DATASET INFORMATION
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("CLEANED DATASETS")
print("=" * 60)

for name, df in tables.items():
    print(
        f"{name:20} : "
        f"{df.shape[0]:,} rows × "
        f"{df.shape[1]} columns"
    )

Clean data directory:
/content/drive/MyDrive/Labmentix Projects/Vaccination_Data_Analysis/cleaned_data

Database:
/content/drive/MyDrive/Labmentix Projects/Vaccination_Data_Analysis/cleaned_data/vaccination.db

============================================================
CLEANED DATASETS
============================================================
coverage             : 399,859 rows × 12 columns
schedule             : 8,053 rows × 12 columns
introduction         : 138,321 rows × 6 columns
cases                : 84,870 rows × 8 columns
incidence            : 84,946 rows × 9 columns

In [ ]:
for name, df in tables.items():

    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)

    print(df.columns.tolist())

============================================================
COVERAGE
============================================================
['group', 'iso_code', 'name', 'year', 'antigen', 'antigen_description', 'coverage_category', 'coverage_category_description', 'target_number', 'doses', 'coverage', 'group_level']

============================================================
SCHEDULE
============================================================
['iso_code', 'countryname', 'who_region', 'year', 'vaccinecode', 'vaccine_description', 'schedulerounds', 'targetpop', 'targetpop_description', 'geoarea', 'ageadministered', 'sourcecomment']

============================================================
INTRODUCTION
============================================================
['iso_code', 'countryname', 'who_region', 'year', 'description', 'intro']

============================================================
CASES
============================================================
['group', 'iso_code', 'name', 'year', 'disease', 'disease_description', 'cases', 'group_level']

============================================================
INCIDENCE
============================================================
['group', 'iso_code', 'name', 'year', 'disease', 'disease_description', 'denominator', 'incidence_rate', 'group_level']

In [ ]:
def standardize_columns(df):

    df = df.copy()

    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )

    return df


for name in tables:

    tables[name] = standardize_columns(
        tables[name]
    )

In [ ]:
for name, df in tables.items():
    print(name, "->")
    print(df.columns.tolist())

coverage ->
['group', 'iso_code', 'name', 'year', 'antigen', 'antigen_description', 'coverage_category', 'coverage_category_description', 'target_number', 'doses', 'coverage', 'group_level']
schedule ->
['iso_code', 'countryname', 'who_region', 'year', 'vaccinecode', 'vaccine_description', 'schedulerounds', 'targetpop', 'targetpop_description', 'geoarea', 'ageadministered', 'sourcecomment']
introduction ->
['iso_code', 'countryname', 'who_region', 'year', 'description', 'intro']
cases ->
['group', 'iso_code', 'name', 'year', 'disease', 'disease_description', 'cases', 'group_level']
incidence ->
['group', 'iso_code', 'name', 'year', 'disease', 'disease_description', 'denominator', 'incidence_rate', 'group_level']